name: CI Pipeline

on:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # This is where tests can be added for each commit
    - name: Run a simple command
      run: echo "Status check placeholder"

