name: Display Ref Name

on:
  push:
    branches:
      - "*" # Trigger on any branch push
  pull_request:
    branches:
      - "*" # Trigger on any branch for pull requests

jobs:
  show-ref-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Display ref_name
        run: echo "The ref name is ${{ github.ref_name }}"
